version: '3'

services:
  client:
    image: node:10.19.0-alpine
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: client
    environment:
      - PORT=3000
    ports:
      - '${CLIENT_PORT}:3000'
    volumes:
      - './node_modules:/home/node/node_modules'
      - './app/node_modules:/home/node/app/node_modules'
      - './app/.next:/home/node/app/.next'
      - './packages/core/node_modules:/home/node/packages/core/node_modules'
    working_dir: /home/node
    command: sh -c "yarn install --frozen-lockfile && yarn dev"
