version: "3"

services:
    client:
        image: node:10.19.0-alpine
        container_name: client
        ports:
            - "${CLIENT_PORT}:${CLIENT_PORT}"
        volumes:
            - "./client/:/usr/src/app"
            - "./client/node_modules:/usr/src/app/node_modules"
        working_dir: /usr/src/app
        command: sh -c "yarn && yarn start"
