version: '3'

services:
  app:
    container_name: keebify-app
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - '127.0.0.1:${HOST_PORT}:3000'
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
      - SERVER_PORT=3000
