ARG NODE_VERSION=10.19.0

# PACKAGES
FROM node:${NODE_VERSION}-alpine AS packages

WORKDIR /home/node

ADD --chown=node:node /package.json /yarn.lock /tsconfig.base.json ./
ADD --chown=node:node /app ./app
ADD --chown=node:node /packages ./packages

USER node

RUN yarn install --frozen-lockfile --no-cache
RUN yarn build

CMD [ "sh", "-c", "yarn start" ]
