version: "3"

services:
    app:
        container_name: app
        build: .
        user: "node"
        ports:
            - "127.0.0.1:${HOST_PORT}:80"
        volumes:
            - "./client/:/home/node/app/client"
            - "./server/:/home/node/app/server"
            - "./client/node_modules:/home/node/app/client/node_modules"
        environment:
            - NODE_ENV=production
            - GENERATE_SOURCEMAP=false
            - SERVER_PORT=80
        command: yarn start
