version: "3"

services:
    app:
        container_name: app
        build: ./
        expose:
            - "${CLIENT_APP_PORT}"
        environment:
            - NODE_ENV=production
            - GENERATE_SOURCEMAP=false
            - SERVER_PORT=${CLIENT_APP_PORT}
        command: yarn start
        networks:
            - app-network
    nginx:
        image: nginx:1.17.8-alpine
        container_name: nginx
        ports:
            - "${NGINX_PORT}:80"
        environment:
            - HOST=${NGINX_HOST}
            - PROXY=http://app:${CLIENT_APP_PORT}
        volumes:
            - "./nginx/default.template:/etc/nginx/conf.d/default.template"
        command:
            /bin/ash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf &&
            exec nginx -g 'daemon off;'"
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
