version: "3"

services:
    app:
        container_name: app
        build: .
        user: "node"
        ports:
            - "127.0.0.1:${HOST_PORT}:80"
        environment:
            - NODE_ENV=production
            - GENERATE_SOURCEMAP=false
            - SERVER_PORT=80
        command: yarn start
